/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ee.schimke.flexpress.codegen

import com.google.common.truth.Truth.assertThat
import ee.schimke.flexpress.testFonts
import java.io.File
import java.nio.file.Files
import org.junit.Test

/** [VariableFontCodegen.write] writes into the package's directory and reports stale sources. */
class VariableFontCodegenWriteTest {
  private val root: File = Files.createTempDirectory("codegen").toFile()
  private val file = File(root, "com/example/text/Brand.kt")

  private fun write(text: String = "Brand", update: Boolean = true) =
    VariableFontCodegen.write(
      root,
      "com.example.text",
      "Brand",
      testFonts[1].font,
      "Roboto Flex",
      text,
      listOf("wght"),
      fileHeader = "// Copyright Example",
      update = update,
    )

  @Test
  fun writesThenReportsUpToDate() {
    assertThat(write()).isFalse()
    assertThat(file.readText()).startsWith("// Copyright Example\n\n// Generated by")
    assertThat(file.readText()).contains("internal fun Brand(")
    assertThat(write()).isTrue()
  }

  @Test
  fun checkingDoesNotWrite() {
    assertThat(write(update = false)).isFalse()
    assertThat(file.exists()).isFalse()
    write()
    assertThat(write("Other", update = false)).isFalse()
    assertThat(file.readText()).contains("\"Brand\"")
  }

  @Test
  fun noHeaderByDefault() {
    val source =
      VariableFontCodegen.generate(
        "com.example",
        "Brand",
        testFonts[1].font,
        "Roboto Flex",
        "Brand",
        listOf("wght"),
      )
    assertThat(source).startsWith("// Generated by VariableFontCodegen")
  }
}
