name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5
      - name: Format
        run: ./gradlew ktfmtCheck
      - name: API
        run: ./gradlew metalavaCheckCompatibility
      - name: Test
        run: ./gradlew test
      - name: Lint
        run: ./gradlew lintDebug
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: reports
          path: '**/build/reports'
